services:
  nginx:
    image: nginx:alpine
    container_name: short-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/data/www
    depends_on:
      - short
    networks:
      - short
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  short:
    container_name: short-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - short
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "400MB"

networks:
  short:
    driver: bridge